// packages/vue/src/lib/stroke/SvStackStroke.vue
<script lang="ts" setup>
const props = defineProps<{
  size?: string
  color?: string
  strokeWidth?: string
}>()
</script>

<template>
  <svg
    viewBox="0 0 24 24"
    fill="none"
    :style="`width: ${props.size}; height: ${props.size}; color: ${props.color}`"
  >
    <path
      d="M4.49996 12L12 15.5L19.5 12M19.5 16L12 19.5L4.50002 16M12 4.5L4.50002 8L12 11.5L19.5 8L12 4.5Z"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      :stroke-width="props.strokeWidth"
    />
  </svg>
</template>

// src/lib/stroke/SvStackStroke.svelte
<script lang="ts">
export let size: string = '100%'
export let color: string = 'currentColor'
export let strokeWidth: string = '1px'
</script>
  
<svg style="color: {color}; width: {size}; height: {size}" viewBox="0 0 24 24" fill="none">
  <path
    d="M4.49996 12L12 15.5L19.5 12M19.5 16L12 19.5L4.50002 16M12 4.5L4.50002 8L12 11.5L19.5 8L12 4.5Z"
    stroke="currentColor"
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="{strokeWidth}"
  />
</svg>
